export enum OrderStatus {
    SEND_BOX = "SEND_BOX",
    SEND_PICKUP = "SEND_PICKUP",
    IN_STORAGE = "IN_STORAGE",
    FULFILLED = "FULFILLED",
    CANCELLED = "CANCELLED",
    RECYCLE = "RECYCLE",
}